"use client"

import jsPDF, { GState } from "jspdf"

interface Props {
  receiptId: string
}

type PdfSetting = {
  companyName?: string | null
  companyEmail?: string | null
  companyPhone?: string | null
  companyAddress?: string | null
  companyCity?: string | null
  companyRegion?: string | null
  companyCountry?: string | null
  companyPostalCode?: string | null
  companyTaxId?: string | null
  companyRegistration?: string | null
  companyWebsite?: string | null
  companyLogo?: string | null
  signatureImageUrl?: string | null
  documentFont?: string | null
}

async function getBase64ImageFromUrl(url: string) {
  const response = await fetch(url, { cache: "no-store" })
  if (!response.ok) throw new Error("Failed to load image")
  const blob = await response.blob()
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      if (typeof reader.result === "string") resolve(reader.result)
      else reject(new Error("Failed to convert image to base64"))
    }
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

function imageType(dataUrl: string) {
  return dataUrl.startsWith("data:image/jpeg") || dataUrl.startsWith("data:image/jpg") ? "JPEG" : "PNG"
}

function clean(value: unknown, fallback = "-") {
  const text = String(value ?? "").trim()
  return text || fallback
}

function money(value: unknown, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
  }).format(Number(value || 0))
}

function companyAddress(setting: PdfSetting) {
  return [
    setting.companyAddress,
    setting.companyCity,
    setting.companyRegion,
    setting.companyCountry,
    setting.companyPostalCode,
  ].filter(Boolean).join(", ")
}

function drawImageContain(doc: jsPDF, dataUrl: string, x: number, y: number, maxWidth: number, maxHeight: number) {
  const props = doc.getImageProperties(dataUrl)
  const ratio = Math.min(maxWidth / props.width, maxHeight / props.height)
  const width = props.width * ratio
  const height = props.height * ratio
  doc.addImage(dataUrl, imageType(dataUrl), x + (maxWidth - width) / 2, y + (maxHeight - height) / 2, width, height)
}

function tryWithOpacity(doc: jsPDF, opacity: number, draw: () => void) {
  try {
    doc.setGState(new GState({ opacity }))
    draw()
    doc.setGState(new GState({ opacity: 1 }))
    return true
  } catch {
    doc.setGState(new GState({ opacity: 1 }))
    return false
  }
}

function drawWatermark(doc: jsPDF, logoData: string | null, companyName: string) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  if (logoData) {
    const rendered = tryWithOpacity(doc, 0.075, () => {
      drawImageContain(doc, logoData, pageWidth / 2 - 138, pageHeight / 2 - 118, 276, 236)
    })
    if (rendered) return
  }

  doc.setTextColor(238, 238, 238)
  doc.setFont("Helvetica", "bold")
  doc.setFontSize(48)
  doc.text(companyName.slice(0, 28).toUpperCase(), pageWidth / 2, pageHeight / 2, {
    align: "center",
    angle: -28,
  })
}

function drawShell(doc: jsPDF, setting: PdfSetting, logoData: string | null, receiptNumber: string) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const companyName = clean(setting.companyName, "Company")

  drawWatermark(doc, logoData, companyName)

  doc.setFillColor(18, 18, 18)
  doc.rect(0, 0, pageWidth, 12, "F")

  if (logoData) {
    drawImageContain(doc, logoData, 40, 30, 116, 44)
  } else {
    doc.setFillColor(18, 18, 18)
    doc.roundedRect(40, 30, 44, 44, 8, 8, "F")
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(18)
    doc.setFont("Helvetica", "bold")
    doc.text(companyName.slice(0, 1).toUpperCase(), 62, 58, { align: "center" })
  }

  doc.setFont("Helvetica", "bold")
  doc.setFontSize(10)
  doc.setTextColor(17, 24, 39)
  doc.text(companyName, 170, 40)
  doc.setFont("Helvetica", "normal")
  doc.setTextColor(100, 116, 139)
  doc.text(clean(setting.companyEmail, ""), 170, 56)
  doc.text([setting.companyPhone, setting.companyWebsite].filter(Boolean).join(" | "), 170, 70)

  doc.setFont("Helvetica", "bold")
  doc.setFontSize(24)
  doc.setTextColor(17, 24, 39)
  doc.text("RECEIPT", pageWidth - 40, 42, { align: "right" })
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(receiptNumber, pageWidth - 40, 62, { align: "right" })

  doc.setDrawColor(226, 232, 240)
  doc.line(40, 96, pageWidth - 40, 96)
  doc.line(40, pageHeight - 44, pageWidth - 40, pageHeight - 44)

  doc.setFont("Helvetica", "normal")
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text(`${companyName} | Payment receipt generated by Astro city crm`, 40, pageHeight - 26)
  doc.text("Original receipt", pageWidth - 40, pageHeight - 26, { align: "right" })
}

function drawDetailRow(doc: jsPDF, label: string, value: string, x: number, y: number, width: number) {
  doc.setFillColor(248, 250, 252)
  doc.setDrawColor(226, 232, 240)
  doc.roundedRect(x, y, width, 42, 7, 7, "FD")
  doc.setFont("Helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text(label.toUpperCase(), x + 12, y + 16)
  doc.setFont("Helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(17, 24, 39)
  doc.text(doc.splitTextToSize(value, width - 24), x + 12, y + 31)
}

function normalizeSetting(receipt: any, fallback: PdfSetting): PdfSetting {
  const company = receipt.company || {}
  const setting = company.settings || fallback || {}
  return {
    ...setting,
    companyName: setting.companyName || company.name || fallback.companyName,
    companyEmail: setting.companyEmail || company.email || fallback.companyEmail,
    companyPhone: setting.companyPhone || company.phone || fallback.companyPhone,
    companyAddress: setting.companyAddress || company.address || fallback.companyAddress,
    companyCity: setting.companyCity || company.city || fallback.companyCity,
    companyRegion: setting.companyRegion || company.region || fallback.companyRegion,
    companyCountry: setting.companyCountry || company.country || fallback.companyCountry,
    companyPostalCode: setting.companyPostalCode || company.postalCode || fallback.companyPostalCode,
    companyTaxId: setting.companyTaxId || company.taxId || fallback.companyTaxId,
    companyRegistration: setting.companyRegistration || company.registrationNumber || fallback.companyRegistration,
    companyWebsite: setting.companyWebsite || company.website || fallback.companyWebsite,
    companyLogo: setting.companyLogo || company.logoUrl || fallback.companyLogo,
    signatureImageUrl: receipt.signatureImageUrl || setting.signatureImageUrl || fallback.signatureImageUrl,
  }
}

export default function DownloadReceiptPdf({ receiptId }: Props) {
  async function handleDownload() {
    try {
      const [receiptRes, settingsRes] = await Promise.all([
        fetch(`/api/receipts/${receiptId}`, { credentials: "include" }),
        fetch(`/api/settings`, { credentials: "include" }),
      ])

      if (!receiptRes.ok) throw new Error("Failed to load receipt")

      const receiptJson = await receiptRes.json()
      const settingsJson = settingsRes.ok ? await settingsRes.json() : { data: {} }
      const receipt = receiptJson.data
      if (!receipt) return alert("Receipt not found")

      const setting = normalizeSetting(receipt, settingsJson.data || {})
      const fontName = ["Helvetica", "Times", "Courier"].includes(clean(setting.documentFont, "Helvetica"))
        ? clean(setting.documentFont, "Helvetica")
        : "Helvetica"

      const doc = new jsPDF({ unit: "pt" })
      doc.setFont(fontName)

      let logoData: string | null = null
      if (setting.companyLogo) {
        try {
          logoData = await getBase64ImageFromUrl(setting.companyLogo)
        } catch (error) {
          console.warn("Could not render company logo", error)
        }
      }

      drawShell(doc, setting, logoData, receipt.receiptNumber || "Receipt")

      const pageWidth = doc.internal.pageSize.getWidth()
      const currency = receipt.currency || receipt.quotation?.currency || settingsJson.data?.defaultCurrency || "USD"
      const customerName = receipt.customer?.companyName || receipt.customer?.contactPerson || "Customer"
      const address = companyAddress(setting)

      doc.setFillColor(240, 253, 244)
      doc.setDrawColor(187, 247, 208)
      doc.roundedRect(40, 120, pageWidth - 80, 104, 12, 12, "FD")
      doc.setTextColor(22, 101, 52)
      doc.setFont("Helvetica", "bold")
      doc.setFontSize(11)
      doc.text("PAYMENT RECEIVED", 60, 148)
      doc.setFontSize(30)
      doc.text(money(receipt.amount, currency), 60, 188)
      doc.setFontSize(10)
      doc.setTextColor(21, 128, 61)
      doc.text(`Paid on ${new Date(receipt.createdAt).toLocaleString()}`, 60, 208)

      doc.setFillColor(22, 101, 52)
      doc.roundedRect(pageWidth - 165, 148, 105, 32, 16, 16, "F")
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(12)
      doc.text("PAID", pageWidth - 112, 169, { align: "center" })

      drawDetailRow(doc, "Receipt number", clean(receipt.receiptNumber), 40, 250, 245)
      drawDetailRow(doc, "Quotation", clean(receipt.quotation?.quotationNumber), 310, 250, 245)
      drawDetailRow(doc, "Customer", customerName, 40, 306, 245)
      drawDetailRow(doc, "Payment method", clean(receipt.paymentMethod), 310, 306, 245)
      drawDetailRow(doc, "Provider", clean(receipt.provider || "MANUAL"), 40, 362, 245)
      drawDetailRow(doc, "Reference", clean(receipt.reference), 310, 362, 245)

      doc.setFillColor(255, 255, 255)
      doc.setDrawColor(226, 232, 240)
      doc.roundedRect(40, 438, pageWidth - 80, 118, 10, 10, "FD")
      doc.setTextColor(17, 24, 39)
      doc.setFont("Helvetica", "bold")
      doc.setFontSize(11)
      doc.text("Company details", 60, 466)
      doc.setFont("Helvetica", "normal")
      doc.setFontSize(9)
      doc.setTextColor(71, 85, 105)
      const companyLines = [
        clean(setting.companyName, "Company"),
        address,
        setting.companyTaxId ? `Tax ID: ${setting.companyTaxId}` : "",
        setting.companyRegistration ? `Registration: ${setting.companyRegistration}` : "",
      ].filter(Boolean)
      doc.text(companyLines, 60, 486)

      doc.setFont("Helvetica", "bold")
      doc.setTextColor(17, 24, 39)
      doc.text("Notes", 330, 466)
      doc.setFont("Helvetica", "normal")
      doc.setTextColor(71, 85, 105)
      const notes = doc.splitTextToSize(clean(receipt.notes, "Payment has been received and recorded."), 205)
      doc.text(notes, 330, 486)

      const signatureY = 650
      const signatureImageUrl = setting.signatureImageUrl
      if (signatureImageUrl) {
        try {
          const signatureData = await getBase64ImageFromUrl(signatureImageUrl)
          drawImageContain(doc, signatureData, 40, signatureY - 44, 136, 44)
        } catch (error) {
          console.warn("Could not render signature", error)
        }
      }

      doc.setDrawColor(17, 24, 39)
      doc.line(40, signatureY, 200, signatureY)
      doc.setFont("Helvetica", "normal")
      doc.setFontSize(9)
      doc.setTextColor(100, 116, 139)
      doc.text("Authorized signature", 40, signatureY + 16)

      doc.setDrawColor(17, 24, 39)
      doc.line(pageWidth - 200, signatureY, pageWidth - 40, signatureY)
      doc.text("Customer acknowledgement", pageWidth - 200, signatureY + 16)

      doc.setFillColor(248, 250, 252)
      doc.setDrawColor(226, 232, 240)
      doc.roundedRect(40, 704, pageWidth - 80, 44, 8, 8, "FD")
      doc.setTextColor(100, 116, 139)
      doc.setFontSize(9)
      doc.text("This receipt confirms that the payment above was recorded for the referenced quotation.", 60, 730)

      doc.save(`${receipt.receiptNumber || "receipt"}.pdf`)
    } catch (err) {
      console.error(err)
      alert("Failed to generate receipt PDF")
    }
  }

  return (
    <button onClick={handleDownload} className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-sm font-medium transition-colors hover:bg-slate-200">
      Download PDF
    </button>
  )
}
